version: "3.7"

services:
  vue3:  
    image: vue_escuela_vuex
    container_name: vue_escuela_vuex
    build: .
    ports:
      - "9000:80"
      - "9091:8080"
    volumes:
      - './vue3:/usr/local/apache2/htdocs/'
    #restart: always
